namespace NcSender.Core.Constants;

public static class GrblErrors
{
    private static readonly IReadOnlyDictionary<int, string> Errors = new Dictionary<int, string>
    {
        [1] = "G-code words consist of a letter and a value. Letter was not found.",
        [2] = "Missing the expected G-code word value or numeric value format is not valid.",
        [3] = "Grbl '$' system command was not recognized or supported.",
        [4] = "Negative value received for an expected positive value.",
        [5] = "Homing cycle failure. Homing is not enabled via settings.",
        [6] = "Minimum step pulse time must be greater than 3usec.",
        [7] = "An EEPROM read failed. Auto-restoring affected EEPROM to default values.",
        [8] = "Grbl '$' command cannot be used unless Grbl is IDLE. Ensures smooth operation during a job.",
        [9] = "G-code commands are locked out during alarm or jog state.",
        [10] = "Soft limits cannot be enabled without homing also enabled.",
        [11] = "Max characters per line exceeded. Received command line was not executed.",
        [12] = "Grbl '$' setting value cause the step rate to exceed the maximum supported.",
        [13] = "Safety door detected as opened and door state initiated.",
        [14] = "Build info or startup line exceeded EEPROM line length limit. Line not stored.",
        [15] = "Jog target exceeds machine travel. Jog command has been ignored.",
        [16] = "Jog command has no '=' or contains prohibited g-code.",
        [17] = "Laser mode requires PWM output.",
        [20] = "Unsupported or invalid g-code command found in block.",
        [21] = "More than one g-code command from same modal group found in block.",
        [22] = "Feed rate has not yet been set or is undefined.",
        [23] = "G-code command in block requires an integer value.",
        [24] = "More than one g-code command that requires axis words found in block.",
        [25] = "Repeated g-code word found in block.",
        [26] = "No axis words found in block for g-code command or current modal state which requires them.",
        [27] = "Line number value is invalid.",
        [28] = "G-code command is missing a required value word.",
        [29] = "G59.x work coordinate systems are not supported.",
        [30] = "G53 only allowed with G0 and G1 motion modes.",
        [31] = "Axis words found in block when no command or current modal state uses them.",
        [32] = "G2 and G3 arcs require at least one in-plane axis word.",
        [33] = "Motion command target is invalid.",
        [34] = "Arc radius value is invalid.",
        [35] = "G2 and G3 arcs require at least one in-plane offset word.",
        [36] = "Unused value words found in block.",
        [37] = "G43.1 dynamic tool length offset is not assigned to configured tool length axis.",
        [38] = "Tool number greater than max supported value.",
        // grblHAL extensions (core/errors.h status_code_t)
        [39] = "Value out of range.",
        [40] = "Tool change: G43.1 dynamic tool length offset is not assigned to configured tool length axis, or tool number is invalid.",
        [41] = "Value word conflict.",
        [42] = "Power on self test failed.",
        [43] = "Emergency stop is active. Clear it and reset the controller.",
        [44] = "Motor fault.",
        [45] = "Setting value is out of range.",
        [46] = "Setting is disabled.",
        [47] = "Invalid retract position for G28 or G30.",
        [48] = "Illegal homing configuration.",
        [49] = "Coordinate system is locked.",
        [50] = "Unsupported IO option.",
        [51] = "Unknown modal group.",
        [52] = "Object counter is not available.",
        [53] = "Non-alphanumeric character in name.",
        [54] = "SD card: unsupported file type.",
        [55] = "SD card: invalid file name or path.",
        [60] = "SD card: mount failed.",
        [61] = "SD card: read failed.",
        [62] = "SD card: failed to open directory.",
        [63] = "SD card: directory not found.",
        [64] = "SD card: file is empty.",
        [65] = "SD card: file not found.",
        [66] = "SD card: file open/read failed.",
        [67] = "SD card: directory listing failed.",
        [70] = "Bluetooth initialisation failed.",
        [71] = "Expression: unknown operator.",
        [72] = "Expression: divide by zero.",
        [73] = "Expression: argument out of range.",
        [74] = "Expression: invalid argument.",
        [75] = "Expression: syntax error.",
        [76] = "Expression: invalid result.",
        [77] = "Authentication required.",
        [78] = "Access denied.",
        [79] = "Not allowed while a critical event such as E-stop or a motor fault is active. Clear it, then reset and unlock.",
        [80] = "Flow control: not executing a macro.",
        [81] = "Flow control: syntax error.",
        [82] = "Flow control: stack overflow.",
        [83] = "Flow control: out of memory.",
        [84] = "File read error.",
        [85] = "Flow control: unexpected end of file.",
    };

    public static string GetMessage(int code) =>
        Errors.TryGetValue(code, out var message) ? message : "Unknown error";
}
